cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    charlie:
      email: ka175896@npc.com.tw
      failed_login_attempts: 0
      logged_in: false
      name: charlie
      password: $2b$12$qrOSAxosHjt6RYwvEzEjSe4sSO46TEduBSsei8pUmKAkJ7XLxVLFK
    n000191032:
      email: N000191032@npc.com.tw
      logged_in: false
      name: Valerie
      password: $2b$12$m6AbLldGPdJSLviHWhyj/.3xqZu9bfV4v5DvL93RAedto9jd5JFY6
pre-authorized:
  emails:
  - N000192076@npc.com.tw
  - N000192234@npc.com.tw
