cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    charlie:
      email: ka175896@npc.com.tw
      logged_in: false
      name: charlie
      password: $2b$12$qrOSAxosHjt6RYwvEzEjSe4sSO46TEduBSsei8pUmKAkJ7XLxVLFK
pre-authorized:
  emails: []
